# Pandas

**Pandas** is one of the most widely used Python libraries for data analysis and manipulation. It provides powerful and easy-to-use data structures, such as **Series** and **DataFrames**, which allow you to load, clean, organize, analyze, and visualize structured data efficiently.

I encourage you to visit the following notebook for more information:
https://github.com/ageron/handson-ml3/blob/main/tools_pandas.ipynb

**Data Structures**: Pandas offers two primary data structures - DataFrame and Series.

1. A DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

2. A Series is a one-dimensional labeled array, essentially a single column or row of data.

## Importing Pandas
Import Pandas using the `import` command, followed by the library's name. Commonly, Pandas is imported as `pd` for brevity in code.

In [2]:
import pandas as pd

## Data Loading
- Pandas can be used to load data from various sources, such as CSV and Excel files.

- The read_csv function is used to load data from a CSV file into a Pandas DataFrame.

To read a CSV (Comma-Separated Values) file in Python using the Pandas library, you can use the `pd.read_csv()` function. Here's the syntax to read a CSV file:

In [10]:
df = pd.read_csv('my_file.csv')

Replace 'your_file.csv' with the actual file path of your CSV file. Make sure that the file is located in the same directory as your Python script, or you provide the **correct** file path.

## What is a Series?

A **Series** is a one-dimensional labeled data structure provided by Pandas. It can store values of any data type, and each value is associated with an **index** that is used to identify and access the data. You can think of a Series as a single column of a table.

In [12]:
import pandas as pd
# Create a Series from a list
data = [10, 20, 30, 40, 50]
s1 = pd.Series(data)
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### **Index labels**
Each item in a `Series` object has a unique identifier called the index label. By default, it is simply the rank of the item in the `Series` (starting from `0`) but you can also set the index labels manually:

In [13]:
s2 = pd.Series([68, 83, 112, 68], index=["alice", "bob", "charles", "darwin"])
s2

alice       68
bob         83
charles    112
darwin      68
dtype: int64

You can then use `Series` just like a `dict`:

In [15]:
s2['bob']

np.int64(83)


To make it clear when you are accessing by label or by integer location, it is recommended to **always** use the `loc` attribute when accessing by label, and the `iloc` attribute when accessing by integer location:

In [16]:
# access by integer
s2.iloc[2]

np.int64(112)

In [17]:
# acces by label
s2.loc['charles']

np.int64(112)

Slicing a `Series` also slices the index labels:

In [21]:
s2.iloc[2:]

charles    112
darwin      68
dtype: int64

## Useful Series Attributes and Methods

Pandas **Series** provide many built-in **attributes** and **methods** that make data exploration and manipulation much easier.

- **Attributes** store information about the Series, such as its size or index. They are accessed without parentheses (e.g., `series.size`).
- **Methods** perform an action or computation, such as calculating the mean or sorting the data. They are called using parentheses (e.g., `series.mean()`).

Some of the most commonly used attributes and methods are:

- **`values`**: Returns the data as a NumPy array.
- **`index`**: Returns the labels (index) of the Series.
- **`shape`**: Returns a tuple representing the dimensions of the Series.
- **`size`**: Returns the total number of elements.

### Statistical methods

- **`mean()`**: Returns the average of the values.
- **`sum()`**: Returns the sum of all values.
- **`min()`**: Returns the smallest value.
- **`max()`**: Returns the largest value.

### Working with unique values

- **`unique()`**: Returns the distinct values in the Series.
- **`nunique()`**: Returns the number of distinct values.

### Sorting

- **`sort_values()`**: Sorts the Series according to its values.
- **`sort_index()`**: Sorts the Series according to its index labels.

### Handling missing values

- **`isnull()`**: Returns `True` for missing (`NaN`) values and `False` otherwise.
- **`notnull()`**: Returns `True` for non-missing values and `False` otherwise.

### Applying custom functions

- **`apply()`**: Applies a user-defined function to every element of the Series.

In [32]:
# Create a Series with a custom index and a missing value
s3 = pd.Series(
    [85, 90, 78, 90, np.nan, 95],
    index=["Alice", "Bob", "Charlie", "David", "Emma", "Frank"]
)

print("Original Series:")
print(s3)

Original Series:
Alice      85.0
Bob        90.0
Charlie    78.0
David      90.0
Emma        NaN
Frank      95.0
dtype: float64

In [33]:
# Series attributes

print("Values:")
print(s3.values)

print("\nIndex:")
print(s3.index)

print("\nShape:")
print(s3.shape)

print("\nSize:")
print(s3.size)

Values:
[85. 90. 78. 90. nan 95.]

Index:
Index(['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank'], dtype='str')

Shape:
(6,)

Size:
6

In [34]:
# Statistical methods

print("Mean:")
print(s3.mean())

print("\nSum:")
print(s3.sum())

print("\nMinimum value:")
print(s3.min())

print("\nMaximum value:")
print(s3.max())

Mean:
87.6

Sum:
438.0

Minimum value:
78.0

Maximum value:
95.0

In [35]:
# Unique values

print("\nUnique values:")
print(s3.unique())

print("\nNumber of unique values:")
print(s3.nunique())

Unique values:
[85. 90. 78. nan 95.]

Number of unique values:
4

In [36]:
# Sorting

print("Sorted by values:")
print(s3.sort_values())

print("\nSorted by index:")
print(s3.sort_index())

Sorted by values:
Charlie    78.0
Alice      85.0
Bob        90.0
David      90.0
Frank      95.0
Emma        NaN
dtype: float64

Sorted by index:
Alice      85.0
Bob        90.0
Charlie    78.0
David      90.0
Emma        NaN
Frank      95.0
dtype: float64

In [37]:
# Missing values

print("Missing values:")
print(s3.isnull())

print("\nNon-missing values:")
print(s3.notnull())

Missing values:
Alice      False
Bob        False
Charlie    False
David      False
Emma        True
Frank      False
dtype: bool

Non-missing values:
Alice       True
Bob         True
Charlie     True
David       True
Emma       False
Frank       True
dtype: bool

In [39]:
# Apply a custom function

def add_five(value):
    return value + 5

print("Add 5 to each value:")
print(s3.apply(add_five))

Add 5 to each value:
Alice       90.0
Bob         95.0
Charlie     83.0
David       95.0
Emma         NaN
Frank      100.0
dtype: float64

## What is a DataFrame?


A **DataFrame** is the primary data structure in Pandas. It represents data in a **two-dimensional table** with labeled rows (index) and labeled columns. Unlike a Series, which stores a single column of data, a DataFrame can contain **multiple columns**, each with its own data type.

DataFrames are widely used for storing, cleaning, analyzing, and manipulating structured data. You can think of a DataFrame as a spreadsheet or a SQL table, but with many powerful tools for data analysis built into Python.

## Creating a DataFrame from a Dictionary

One of the simplest ways to create a DataFrame is from a Python **dictionary**. In this case, each **key** becomes a column name, and each **value** (typically a list or another sequence) becomes the data stored in that column.

All columns should have the same number of elements, since each row represents a single observation.

In [40]:
import pandas as pd

# Create a dictionary
students = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [20, 21, 19, 22],
    "Major": ["Physics", "Mathematics", "Computer Science", "Biology"]
}

# Create a DataFrame from the dictionary
df_students = pd.DataFrame(students)

# Display the DataFrame
df_students

      Name  Age             Major
0    Alice   20           Physics
1      Bob   21       Mathematics
2  Charlie   19  Computer Science
3    Diana   22           Biology

You can also create a DataFrame by passing a dictionary of `Series` objects:

In [41]:
people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
}
people = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

You can access columns pretty much as you would expect. They are returned as `Series` objects:

In [46]:
people['birthyear']

alice      1985
bob        1984
charles    1992
Name: birthyear, dtype: int64

## Accessing Data with `loc` and `iloc`

Pandas provides two main ways to access data in a DataFrame:

- **`loc`** selects rows and columns **by their labels** (index and column names).
- **`iloc`** selects rows and columns **by their integer positions**, starting from `0`.

In general:

- Use **`loc`** when you know the **names** of the rows or columns.
- Use **`iloc`** when you know their **positions** in the DataFrame.

The table below summarizes the main differences:

| `loc` | `iloc` |
| :--- | :--- |
| Uses row and column **labels** | Uses integer **positions** |
| Slice endpoints are **included** | Slice endpoints are **excluded** |
| Example: `df.loc["A", "Name"]` | Example: `df.iloc[0, 0]` |

Using `loc`

In [47]:
# Select the row with label "alice"
people.loc["alice"]

weight           68
birthyear      1985
children        NaN
hobby        Biking
Name: alice, dtype: object

In [48]:
# Select the value at row "bob" and column "weight"
people.loc["bob", "weight"]

np.int64(83)

In [53]:
# Select multiple rows
people.loc[["alice", "charles"]]

         weight  birthyear  children   hobby
alice        68       1985       NaN  Biking
charles     112       1992       0.0     NaN

In [54]:
# Slice rows by their labels (both endpoints are included)
people.loc["alice":"charles"]

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

Using `iloc`

In [55]:
# Select the first row (position 0)
people.iloc[0]

weight           68
birthyear      1985
children        NaN
hobby        Biking
Name: alice, dtype: object

In [56]:
# Select the value at row 1 and column 0
people.iloc[1, 0]

np.int64(83)

In [57]:
# Select specific rows and columns
people.iloc[[0, 1], [0, 1]]

       weight  birthyear
alice      68       1985
bob        83       1984

In [59]:
# Slice rows and columns by their positions (the endpoint is excluded)
people.iloc[0:3, 2:4]

         children    hobby
alice         NaN   Biking
bob           3.0  Dancing
charles       0.0      NaN

## Accessing Columns with `[]`

A DataFrame column can also be accessed using square brackets `[]`. The argument inside the brackets is the **column label**.

When selecting **one column**, Pandas returns a **Series**. If you instead provide a **list of column names**, Pandas returns a **DataFrame** containing only those columns.

This is one of the most common ways to select columns from a DataFrame.

In [60]:
# DataFrame
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [61]:
# Select a single column (returns a Series)
people["weight"]

alice       68
bob         83
charles    112
Name: weight, dtype: int64

In [62]:
# Select multiple columns (returns a DataFrame)
people[["weight", "birthyear"]]

         weight  birthyear
alice        68       1985
bob          83       1984
charles     112       1992